### ISSUE TITLE
pagination page numbers become blue when hovered. remove it

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/dashboard#8]
remove the pagination page number color change when hovered. keep it white.
![image](https://user-images.githubusercontent.com/1659870/66696578-d708bb00-ecff-11e9-8564-e657eeda57f4.png)

**Comment by rajkharvar** [comment]
for only active or for all the page number?

**Comment by hrishikeshio** [comment]
active

**Comment by hrishikeshio** [comment]
solved
